name: SBRateBot V5 GitHub Actions auto update

on:
  schedule:
    - cron: "30 15 * * *"

  workflow_dispatch:

permissions:
  contents: write


jobs:

  update-rate:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install packages
        run: |
          pip install requests urllib3


      - name: Run FSB crawler
        run: |
          python crawler/fsb.py


      - name: Commit updated data
        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add data/latest_rates.json
          git add data/previous_rates.json
          git add data/update_info.json
          git add data/banks.json

          git commit -m "Auto update rates" || echo "No changes"

          git push